spring:
  # Database
  datasource:
    url: jdbc:postgresql://${DATABASE_HOSTNAME:localhost}:${DATABASE_PORT:5432}/postgres?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:postgres}
    password: "012345"
    driver-class-name: org.postgresql.Driver
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect